ARG version
FROM almalinux:${version:-9}
ENV course="devops" \
    trainer="sivakumar" \
    duration="120hrs"
ARG USERNAME=Sivakumar
RUN echo "Hello User: ${USERNAME}, image version: ${version}"" > /tmp/devops.txt
CMD ["sleep","100"]
